/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated.products'
import { Route as AuthenticatedGoldsmithsIndexRouteImport } from './routes/_authenticated.goldsmiths.index'
import { Route as AuthenticatedGoldsmithsIdRouteImport } from './routes/_authenticated.goldsmiths.$id'
import { Route as AuthenticatedGoldsmithsIdBooksBookIdRouteImport } from './routes/_authenticated.goldsmiths.$id.books.$bookId'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/_authenticated/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGoldsmithsIndexRoute =
  AuthenticatedGoldsmithsIndexRouteImport.update({
    id: '/_authenticated/goldsmiths/',
    path: '/goldsmiths/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedGoldsmithsIdRoute =
  AuthenticatedGoldsmithsIdRouteImport.update({
    id: '/_authenticated/goldsmiths/$id',
    path: '/goldsmiths/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedGoldsmithsIdBooksBookIdRoute =
  AuthenticatedGoldsmithsIdBooksBookIdRouteImport.update({
    id: '/books/$bookId',
    path: '/books/$bookId',
    getParentRoute: () => AuthenticatedGoldsmithsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/products': typeof AuthenticatedProductsRoute
  '/': typeof AuthenticatedIndexRoute
  '/goldsmiths/$id': typeof AuthenticatedGoldsmithsIdRouteWithChildren
  '/goldsmiths/': typeof AuthenticatedGoldsmithsIndexRoute
  '/goldsmiths/$id/books/$bookId': typeof AuthenticatedGoldsmithsIdBooksBookIdRoute
}
export interface FileRoutesByTo {
  '/products': typeof AuthenticatedProductsRoute
  '/': typeof AuthenticatedIndexRoute
  '/goldsmiths/$id': typeof AuthenticatedGoldsmithsIdRouteWithChildren
  '/goldsmiths': typeof AuthenticatedGoldsmithsIndexRoute
  '/goldsmiths/$id/books/$bookId': typeof AuthenticatedGoldsmithsIdBooksBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/goldsmiths/$id': typeof AuthenticatedGoldsmithsIdRouteWithChildren
  '/_authenticated/goldsmiths/': typeof AuthenticatedGoldsmithsIndexRoute
  '/_authenticated/goldsmiths/$id/books/$bookId': typeof AuthenticatedGoldsmithsIdBooksBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/products'
    | '/'
    | '/goldsmiths/$id'
    | '/goldsmiths/'
    | '/goldsmiths/$id/books/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/products'
    | '/'
    | '/goldsmiths/$id'
    | '/goldsmiths'
    | '/goldsmiths/$id/books/$bookId'
  id:
    | '__root__'
    | '/_authenticated/products'
    | '/_authenticated/'
    | '/_authenticated/goldsmiths/$id'
    | '/_authenticated/goldsmiths/'
    | '/_authenticated/goldsmiths/$id/books/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGoldsmithsIdRoute: typeof AuthenticatedGoldsmithsIdRouteWithChildren
  AuthenticatedGoldsmithsIndexRoute: typeof AuthenticatedGoldsmithsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/goldsmiths/': {
      id: '/_authenticated/goldsmiths/'
      path: '/goldsmiths'
      fullPath: '/goldsmiths/'
      preLoaderRoute: typeof AuthenticatedGoldsmithsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/goldsmiths/$id': {
      id: '/_authenticated/goldsmiths/$id'
      path: '/goldsmiths/$id'
      fullPath: '/goldsmiths/$id'
      preLoaderRoute: typeof AuthenticatedGoldsmithsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/goldsmiths/$id/books/$bookId': {
      id: '/_authenticated/goldsmiths/$id/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/goldsmiths/$id/books/$bookId'
      preLoaderRoute: typeof AuthenticatedGoldsmithsIdBooksBookIdRouteImport
      parentRoute: typeof AuthenticatedGoldsmithsIdRoute
    }
  }
}

interface AuthenticatedGoldsmithsIdRouteChildren {
  AuthenticatedGoldsmithsIdBooksBookIdRoute: typeof AuthenticatedGoldsmithsIdBooksBookIdRoute
}

const AuthenticatedGoldsmithsIdRouteChildren: AuthenticatedGoldsmithsIdRouteChildren =
  {
    AuthenticatedGoldsmithsIdBooksBookIdRoute:
      AuthenticatedGoldsmithsIdBooksBookIdRoute,
  }

const AuthenticatedGoldsmithsIdRouteWithChildren =
  AuthenticatedGoldsmithsIdRoute._addFileChildren(
    AuthenticatedGoldsmithsIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGoldsmithsIdRoute: AuthenticatedGoldsmithsIdRouteWithChildren,
  AuthenticatedGoldsmithsIndexRoute: AuthenticatedGoldsmithsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
