/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedWorkStatusRouteImport } from './routes/_authenticated.work-status'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated.products'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated.marketing'
import { Route as AuthenticatedGemstonesRouteImport } from './routes/_authenticated.gemstones'
import { Route as AuthenticatedGoldsmithsIndexRouteImport } from './routes/_authenticated.goldsmiths.index'
import { Route as AuthenticatedProductsPidRouteImport } from './routes/_authenticated.products.$pid'
import { Route as AuthenticatedGoldsmithsIdRouteImport } from './routes/_authenticated.goldsmiths.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminMarketingOrdersRouteImport } from './routes/_authenticated.admin.marketing-orders'
import { Route as AuthenticatedGoldsmithsIdBooksBookIdRouteImport } from './routes/_authenticated.goldsmiths.$id.books.$bookId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkStatusRoute = AuthenticatedWorkStatusRouteImport.update({
  id: '/work-status',
  path: '/work-status',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGemstonesRoute = AuthenticatedGemstonesRouteImport.update({
  id: '/gemstones',
  path: '/gemstones',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoldsmithsIndexRoute =
  AuthenticatedGoldsmithsIndexRouteImport.update({
    id: '/goldsmiths/',
    path: '/goldsmiths/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsPidRoute =
  AuthenticatedProductsPidRouteImport.update({
    id: '/$pid',
    path: '/$pid',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedGoldsmithsIdRoute =
  AuthenticatedGoldsmithsIdRouteImport.update({
    id: '/goldsmiths/$id',
    path: '/goldsmiths/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminMarketingOrdersRoute =
  AuthenticatedAdminMarketingOrdersRouteImport.update({
    id: '/admin/marketing-orders',
    path: '/admin/marketing-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGoldsmithsIdBooksBookIdRoute =
  AuthenticatedGoldsmithsIdBooksBookIdRouteImport.update({
    id: '/books/$bookId',
    path: '/books/$bookId',
    getParentRoute: () => AuthenticatedGoldsmithsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/gemstones': typeof AuthenticatedGemstonesRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/work-status': typeof AuthenticatedWorkStatusRoute
  '/admin/marketing-orders': typeof AuthenticatedAdminMarketingOrdersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/goldsmiths/$id': typeof AuthenticatedGoldsmithsIdRouteWithChildren
  '/products/$pid': typeof AuthenticatedProductsPidRoute
  '/goldsmiths/': typeof AuthenticatedGoldsmithsIndexRoute
  '/goldsmiths/$id/books/$bookId': typeof AuthenticatedGoldsmithsIdBooksBookIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/gemstones': typeof AuthenticatedGemstonesRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/work-status': typeof AuthenticatedWorkStatusRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/marketing-orders': typeof AuthenticatedAdminMarketingOrdersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/goldsmiths/$id': typeof AuthenticatedGoldsmithsIdRouteWithChildren
  '/products/$pid': typeof AuthenticatedProductsPidRoute
  '/goldsmiths': typeof AuthenticatedGoldsmithsIndexRoute
  '/goldsmiths/$id/books/$bookId': typeof AuthenticatedGoldsmithsIdBooksBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/gemstones': typeof AuthenticatedGemstonesRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/products': typeof AuthenticatedProductsRouteWithChildren
  '/_authenticated/work-status': typeof AuthenticatedWorkStatusRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/marketing-orders': typeof AuthenticatedAdminMarketingOrdersRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/goldsmiths/$id': typeof AuthenticatedGoldsmithsIdRouteWithChildren
  '/_authenticated/products/$pid': typeof AuthenticatedProductsPidRoute
  '/_authenticated/goldsmiths/': typeof AuthenticatedGoldsmithsIndexRoute
  '/_authenticated/goldsmiths/$id/books/$bookId': typeof AuthenticatedGoldsmithsIdBooksBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/gemstones'
    | '/marketing'
    | '/products'
    | '/work-status'
    | '/admin/marketing-orders'
    | '/admin/users'
    | '/goldsmiths/$id'
    | '/products/$pid'
    | '/goldsmiths/'
    | '/goldsmiths/$id/books/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/gemstones'
    | '/marketing'
    | '/products'
    | '/work-status'
    | '/'
    | '/admin/marketing-orders'
    | '/admin/users'
    | '/goldsmiths/$id'
    | '/products/$pid'
    | '/goldsmiths'
    | '/goldsmiths/$id/books/$bookId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/gemstones'
    | '/_authenticated/marketing'
    | '/_authenticated/products'
    | '/_authenticated/work-status'
    | '/_authenticated/'
    | '/_authenticated/admin/marketing-orders'
    | '/_authenticated/admin/users'
    | '/_authenticated/goldsmiths/$id'
    | '/_authenticated/products/$pid'
    | '/_authenticated/goldsmiths/'
    | '/_authenticated/goldsmiths/$id/books/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/work-status': {
      id: '/_authenticated/work-status'
      path: '/work-status'
      fullPath: '/work-status'
      preLoaderRoute: typeof AuthenticatedWorkStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gemstones': {
      id: '/_authenticated/gemstones'
      path: '/gemstones'
      fullPath: '/gemstones'
      preLoaderRoute: typeof AuthenticatedGemstonesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goldsmiths/': {
      id: '/_authenticated/goldsmiths/'
      path: '/goldsmiths'
      fullPath: '/goldsmiths/'
      preLoaderRoute: typeof AuthenticatedGoldsmithsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/$pid': {
      id: '/_authenticated/products/$pid'
      path: '/$pid'
      fullPath: '/products/$pid'
      preLoaderRoute: typeof AuthenticatedProductsPidRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/goldsmiths/$id': {
      id: '/_authenticated/goldsmiths/$id'
      path: '/goldsmiths/$id'
      fullPath: '/goldsmiths/$id'
      preLoaderRoute: typeof AuthenticatedGoldsmithsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/marketing-orders': {
      id: '/_authenticated/admin/marketing-orders'
      path: '/admin/marketing-orders'
      fullPath: '/admin/marketing-orders'
      preLoaderRoute: typeof AuthenticatedAdminMarketingOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goldsmiths/$id/books/$bookId': {
      id: '/_authenticated/goldsmiths/$id/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/goldsmiths/$id/books/$bookId'
      preLoaderRoute: typeof AuthenticatedGoldsmithsIdBooksBookIdRouteImport
      parentRoute: typeof AuthenticatedGoldsmithsIdRoute
    }
  }
}

interface AuthenticatedProductsRouteChildren {
  AuthenticatedProductsPidRoute: typeof AuthenticatedProductsPidRoute
}

const AuthenticatedProductsRouteChildren: AuthenticatedProductsRouteChildren = {
  AuthenticatedProductsPidRoute: AuthenticatedProductsPidRoute,
}

const AuthenticatedProductsRouteWithChildren =
  AuthenticatedProductsRoute._addFileChildren(
    AuthenticatedProductsRouteChildren,
  )

interface AuthenticatedGoldsmithsIdRouteChildren {
  AuthenticatedGoldsmithsIdBooksBookIdRoute: typeof AuthenticatedGoldsmithsIdBooksBookIdRoute
}

const AuthenticatedGoldsmithsIdRouteChildren: AuthenticatedGoldsmithsIdRouteChildren =
  {
    AuthenticatedGoldsmithsIdBooksBookIdRoute:
      AuthenticatedGoldsmithsIdBooksBookIdRoute,
  }

const AuthenticatedGoldsmithsIdRouteWithChildren =
  AuthenticatedGoldsmithsIdRoute._addFileChildren(
    AuthenticatedGoldsmithsIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedGemstonesRoute: typeof AuthenticatedGemstonesRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRouteWithChildren
  AuthenticatedWorkStatusRoute: typeof AuthenticatedWorkStatusRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminMarketingOrdersRoute: typeof AuthenticatedAdminMarketingOrdersRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedGoldsmithsIdRoute: typeof AuthenticatedGoldsmithsIdRouteWithChildren
  AuthenticatedGoldsmithsIndexRoute: typeof AuthenticatedGoldsmithsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGemstonesRoute: AuthenticatedGemstonesRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRouteWithChildren,
  AuthenticatedWorkStatusRoute: AuthenticatedWorkStatusRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminMarketingOrdersRoute:
    AuthenticatedAdminMarketingOrdersRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedGoldsmithsIdRoute: AuthenticatedGoldsmithsIdRouteWithChildren,
  AuthenticatedGoldsmithsIndexRoute: AuthenticatedGoldsmithsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
